services:
  - type: web
    name: mental-ai-chatbot-backend
    env: python
    rootDir: python
    buildCommand: pip install -r ../requirements.txt
    startCommand: cd python && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0